// frontend/src/utils/constants/notificationConstants.js

export const NOTIFICATION_TYPES = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  ISSUE_ASSIGNED: 'ISSUE_ASSIGNED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  TASK_STATUS_CHANGED: 'TASK_STATUS_CHANGED',
  ISSUE_STATUS_CHANGED: 'ISSUE_STATUS_CHANGED',
  PROJECT_MEMBER_ADDED: 'PROJECT_MEMBER_ADDED',
};

export const NOTIFICATION_ICONS = {
  [NOTIFICATION_TYPES.TASK_ASSIGNED]: '📋',
  [NOTIFICATION_TYPES.ISSUE_ASSIGNED]: '🐛',
  [NOTIFICATION_TYPES.COMMENT_ADDED]: '💬',
  [NOTIFICATION_TYPES.TASK_STATUS_CHANGED]: '🔄',
  [NOTIFICATION_TYPES.ISSUE_STATUS_CHANGED]: '🔄',
  [NOTIFICATION_TYPES.PROJECT_MEMBER_ADDED]: '👥',
};

export const NOTIFICATION_COLORS = {
  [NOTIFICATION_TYPES.TASK_ASSIGNED]: 'var(--color-primary)',
  [NOTIFICATION_TYPES.ISSUE_ASSIGNED]: 'var(--color-danger)',
  [NOTIFICATION_TYPES.COMMENT_ADDED]: 'var(--color-info)',
  [NOTIFICATION_TYPES.TASK_STATUS_CHANGED]: 'var(--color-warning)',
  [NOTIFICATION_TYPES.ISSUE_STATUS_CHANGED]: 'var(--color-warning)',
  [NOTIFICATION_TYPES.PROJECT_MEMBER_ADDED]: 'var(--color-success)',
};

export const NOTIFICATION_LABELS = {
  [NOTIFICATION_TYPES.TASK_ASSIGNED]: 'Task Assigned',
  [NOTIFICATION_TYPES.ISSUE_ASSIGNED]: 'Issue Assigned',
  [NOTIFICATION_TYPES.COMMENT_ADDED]: 'New Comment',
  [NOTIFICATION_TYPES.TASK_STATUS_CHANGED]: 'Task Status Changed',
  [NOTIFICATION_TYPES.ISSUE_STATUS_CHANGED]: 'Issue Status Changed',
  [NOTIFICATION_TYPES.PROJECT_MEMBER_ADDED]: 'Member Added',
};